apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::062009854040:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1GFN0CWMMUPXP
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::062009854040:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-01T11:46:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "902"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 746ae988-740e-11ea-aa3e-0ace6e40b488
